#!/usr/bin/env bash

# Git
alias ga="git add"
alias gaa="git add --all"
alias gaaacne="git commit --all --amend --no-edit"
alias gaaacv="git commit --all --amend --verbose"
alias gaacv="git commit --all --verbose"
alias gap="git add --patch"
alias gb="git branch"
alias gc="git checkout"
alias gcav="git commit --amend --verbose"
alias gcv="git commit --verbose"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log"
alias gll="git log --oneline --no-show-signature --color | nl | less -R"
alias gp="git push"
alias gpf="git push --force"
alias gr="git reset"
alias grp="git reset --patch"
alias gs="git status"
alias gsh="git show"
alias gshn="git show --name-only --oneline"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gss="git stash save"

# SecureSet
alias ss="cd ~/Sync/secureset && pwd && ls"
alias ssa100="cd ~/Sync/secureset/app/100 && pwd && ls"
alias ssa200="cd ~/Sync/secureset/app/200 && pwd && ls"
alias ssa="cd ~/Sync/secureset/app && pwd && ls"
alias ssc100="cd ~/Sync/secureset/crypto/100 && pwd && ls"
alias ssc200="cd ~/Sync/secureset/crypto/200 && pwd && ls"
alias ssc300="cd ~/Sync/secureset/crypto/300 && pwd && ls"
alias ssc="cd ~/Sync/secureset/crypto && pwd && ls"
alias ssg100="cd ~/Sync/secureset/grc/100 && pwd && ls"
alias ssg200="cd ~/Sync/secureset/grc/200 && pwd && ls"
alias ssg="cd ~/Sync/secureset/grc && pwd && ls"
alias ssl100="cd ~/Sync/secureset/logs/100 && pwd && ls"
alias ssl200="cd ~/Sync/secureset/logs/200 && pwd && ls"
alias ssl="cd ~/Sync/secureset/logs && pwd && ls"
alias ssn100="cd ~/Sync/secureset/net/100 && pwd && ls"
alias ssn200="cd ~/Sync/secureset/net/200 && pwd && ls"
alias ssn300="cd ~/Sync/secureset/net/300 && pwd && ls"
alias ssn400="cd ~/Sync/secureset/net/400 && pwd && ls"
alias ssn500="cd ~/Sync/secureset/net/500 && pwd && ls"
alias ssn="cd ~/Sync/secureset/net && pwd && ls"
alias ssp100="cd ~/Sync/secureset/python/100 && pwd && ls"
alias ssp200="cd ~/Sync/secureset/python/200 && pwd && ls"
alias ssp="cd ~/Sync/secureset/python && pwd && ls"
alias sss100="cd ~/Sync/secureset/sys/100 && pwd && ls"
alias sss200="cd ~/Sync/secureset/sys/200 && pwd && ls"
alias sss300="cd ~/Sync/secureset/sys/300 && pwd && ls"
alias sss400="cd ~/Sync/secureset/sys/400 && pwd && ls"
alias sss500="cd ~/Sync/secureset/sys/500 && pwd && ls"
alias sss="cd ~/Sync/secureset/sys && pwd && ls"
alias sst100="cd ~/Sync/secureset/threat/100 && pwd && ls"
alias sst200="cd ~/Sync/secureset/threat/200 && pwd && ls"
alias sst="cd ~/Sync/secureset/threat && pwd && ls"

# Miscellaneous
alias coa="cd ~/projects/godot/coa && gs"
alias dotfiles="cd ~/projects/dotfiles && gs"
alias ea="vim ~/.bash_aliases"
alias eb="vim ~/.bash_profile"
alias ev="vim ~/.vimrc"
alias ip="curl ifconfig.me"
alias sb="source ~/.bash_profile"
alias website="cd ~/projects/website && gs"
