#!/usr/bin/env bash

# Git
alias ga="git add"
alias gaa="git add --all"
alias gaaacne="git commit --all --amend --no-edit"
alias gaaacv="git commit --all --amend --verbose"
alias gaacv="git commit --all --verbose"
alias gap="git add --patch"
alias gb="git branch"
alias gc="git checkout"
alias gcav="git commit --amend --verbose"
alias gcv="git commit --verbose"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git log"
alias gll="git log --oneline --no-show-signature --color | nl | less -R"
alias glll="git log --stat --oneline --no-show-signature --color | nl | less -R"
alias gpl="git pull"
alias gpp="git push"
alias gppf="git push --force"
alias gprc="gh pr create"
alias gprcf="gh pr create --fill"
alias gpsu="git push --set-upstream origin HEAD"
alias gprm="gh pr merge"
alias gprms="gh pr merge --squash"
alias gprmsd="gh pr merge --squash --delete-branch"
alias gprmsda="gh pr merge --squash --delete-branch --auto"
alias gr="git reset"
alias grp="git reset --patch"
alias gs="git status"
alias gsh="git show"
alias gshn="git show --name-only --oneline --no-show-signature"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gss="git stash save"

# Miscellaneous
alias coa="cd ~/Sync/dev/projects/godot/coa && gs"
alias dotfiles="cd ~/Sync/dev/projects/dotfiles && gs"
alias ea="vim ~/.bash_aliases"
alias ebp="vim ~/.bash_profile"
alias es="vim ~/.vim/spell/en.utf-8.add"
alias ev="vim ~/.vimrc"
alias godot="/Applications/Godot_mono.app/Contents/MacOS/Godot"
alias godot2="cd ~/Sync/dev/projects/godot && ls"
alias ip="curl ifconfig.me"
alias py="cd ~/Sync/dev/projects/python && ls"
alias sbp="source ~/.bash_profile"
alias website="cd ~/Sync/dev/projects/website && gs"
