#!/usr/bin/env bash

# Disable Gatekeeper: Allow applications downloaded from anywhere.
sudo spctl --master-disable

# Disable "This application has been downloaded from the internet..."
# warnings
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Restart Finder to force changes to update.
killall Finder

